#!/usr/bin/env python3
"""
/quick-spec Command
Rapid specification generation for bug fixes and small features
Invokes: Goliath (leader) + Brooklyn (strategist)
"""

import sys
import os

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from clan_wyvern import CastleWyvern


def quick_spec(description):
    """Generate a quick technical specification."""
    wyvern = CastleWyvern()

    print("=== QUICK SPEC COMMAND ===")
    print(f"Task: {description}")
    print()

    # Goliath scopes the work
    print("[GOLIATH]: 'Let me understand what needs to be done...'")
    goliath_prompt = f"""
    A user needs a quick technical spec for: {description}
    
    Provide:
    1. Problem statement (1-2 sentences)
    2. Scope (what's in/out)
    3. Success criteria (how do we know it's done?)
    4. Any risks or concerns
    
    Be concise. This is a quick spec, not a full PRD.
    """

    goliath_response = wyvern.gate._call_zai(goliath_prompt, wyvern.spells["goliath"][:1000])
    print(f"[GOLIATH]: {goliath_response[:500]}...")
    print()

    # Brooklyn provides technical approach
    print("[BROOKLYN]: 'Here's how I'd tackle this...'")
    brooklyn_prompt = f"""
    Based on Goliath's scope, provide a technical approach for: {description}
    
    Include:
    1. Suggested implementation approach
    2. Key files/components to modify
    3. Estimated complexity (Simple/Medium/Complex)
    4. Any dependencies or blockers
    
    Keep it actionable. Lexington will use this to build.
    """

    brooklyn_response = wyvern.gate._call_zai(brooklyn_prompt, wyvern.spells["brooklyn"][:1000])
    print(f"[BROOKLYN]: {brooklyn_response[:500]}...")
    print()

    # Combined spec output
    spec = f"""
# Quick Technical Spec

## Overview
{description}

## Goliath's Scope
{goliath_response}

## Brooklyn's Approach
{brooklyn_response}

## Next Steps
1. Review this spec
2. Run `/dev-story` to implement
3. Run `/code-review` when complete

---
Generated by Castle Wyvern BMAD System
"""

    # Save to file
    spec_file = f"specs/quick_spec_{description.replace(' ', '_')[:30]}.md"
    os.makedirs("specs", exist_ok=True)
    with open(spec_file, "w") as f:
        f.write(spec)

    print(f"✅ Spec saved to: {spec_file}")
    print("\nNext: Run `/dev-story` to implement")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python quick_spec.py 'description of task'")
        print("Example: python quick_spec.py 'fix login button color'")
        sys.exit(1)

    description = " ".join(sys.argv[1:])
    quick_spec(description)
